[package]
name = "tracing-serde-modality-ingest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modality-ingest-protocol = { path = "../../modality-sdk/client-libraries/rust/modality-ingest-client" }
tracing-serde-wire = { path = "../../tracing-playground/crates/tracing-serde-wire/" }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
tracing-serde = { path = "../../tracing-playground/tracing/tracing-serde" }
once_cell = "1.12.0"
